[tool.poetry]
name = "renutil"
version = "1.9.0"
description = "A toolkit for managing Ren'Py instances via the command line"
authors = ["CobaltCore <cobaltcore@yandex.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kobaltcore/renutil"
homepage = "https://github.com/kobaltcore/renutil"

[tool.poetry.scripts]
renutil = "renutil.renutil:cli"

[tool.poetry.dependencies]
python = "^3.5"
semantic_version = "^2.8.4"
lxml = "^4.5.0"
tqdm = "^4.45.0"
click = "^7.1.1"
logzero = "^1.5.0"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.1"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
